FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --force

# El código se monta por volumen en dev
EXPOSE 4200

# Escucha en todas las interfaces (necesario dentro de Docker)
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
